### ISSUE TITLE
Active window having same colour as status bar instead of orange

### ISSUE THREAD

**Issue by alex-schulster** [LawAbidingCactus/tmux-gruvbox-truecolor#3]
The active window indicator in the status bar does not appear orange as it should, but is "transparent" that is gets the same colour as the status bar.

![image](https://user-images.githubusercontent.com/40316586/199046891-91d4a12a-0c6a-41b2-8422-46645902d42c.png)

I checked to config file and the style is defined for the active window.

![image](https://user-images.githubusercontent.com/40316586/199047086-f6f3b5c2-0be4-48db-8555-676eccac7d7f.png)

**Comment by samyak039** [comment]
I'm also facing the same issue. @alex-schulster did you find any fix for this?
